import { SymbolInfo } from '../../src/types/market';

export const SUPPORTED_SYMBOLS: SymbolInfo[] = [
  // ----------------------------------------------------
  // FOREX (Decentralized OTC, Derived Order Flow)
  // ----------------------------------------------------
  {
    id: 'EURUSD',
    displaySymbol: 'EUR/USD',
    name: 'Euro / US Dollar',
    baseAsset: 'EUR',
    quoteAsset: 'USD',
    priceDecimals: 5,
    tickSize: 0.0001,
    defaultPrice: 1.08500,
    category: 'forex',
    tradingViewSymbol: 'FX:EURUSD',
    twelveDataSymbol: 'EUR/USD',
    isDecentralizedOrQuoteOnly: true,
  },
  {
    id: 'GBPUSD',
    displaySymbol: 'GBP/USD',
    name: 'British Pound / US Dollar',
    baseAsset: 'GBP',
    quoteAsset: 'USD',
    priceDecimals: 5,
    tickSize: 0.0001,
    defaultPrice: 1.29400,
    category: 'forex',
    tradingViewSymbol: 'FX:GBPUSD',
    twelveDataSymbol: 'GBP/USD',
    isDecentralizedOrQuoteOnly: true,
  },
  {
    id: 'USDJPY',
    displaySymbol: 'USD/JPY',
    name: 'US Dollar / Japanese Yen',
    baseAsset: 'USD',
    quoteAsset: 'JPY',
    priceDecimals: 3,
    tickSize: 0.01,
    defaultPrice: 152.650,
    category: 'forex',
    tradingViewSymbol: 'FX:USDJPY',
    twelveDataSymbol: 'USD/JPY',
    isDecentralizedOrQuoteOnly: true,
  },
  {
    id: 'USDCHF',
    displaySymbol: 'USD/CHF',
    name: 'US Dollar / Swiss Franc',
    baseAsset: 'USD',
    quoteAsset: 'CHF',
    priceDecimals: 5,
    tickSize: 0.0001,
    defaultPrice: 0.88450,
    category: 'forex',
    tradingViewSymbol: 'FX:USDCHF',
    twelveDataSymbol: 'USD/CHF',
    isDecentralizedOrQuoteOnly: true,
  },
  {
    id: 'AUDUSD',
    displaySymbol: 'AUD/USD',
    name: 'Australian Dollar / US Dollar',
    baseAsset: 'AUD',
    quoteAsset: 'USD',
    priceDecimals: 5,
    tickSize: 0.0001,
    defaultPrice: 0.65800,
    category: 'forex',
    tradingViewSymbol: 'FX:AUDUSD',
    twelveDataSymbol: 'AUD/USD',
    isDecentralizedOrQuoteOnly: true,
  },
  {
    id: 'USDCAD',
    displaySymbol: 'USD/CAD',
    name: 'US Dollar / Canadian Dollar',
    baseAsset: 'USD',
    quoteAsset: 'CAD',
    priceDecimals: 5,
    tickSize: 0.0001,
    defaultPrice: 1.39800,
    category: 'forex',
    tradingViewSymbol: 'FX:USDCAD',
    twelveDataSymbol: 'USD/CAD',
    isDecentralizedOrQuoteOnly: true,
  },
  {
    id: 'NZDUSD',
    displaySymbol: 'NZD/USD',
    name: 'New Zealand Dollar / US Dollar',
    baseAsset: 'NZD',
    quoteAsset: 'USD',
    priceDecimals: 5,
    tickSize: 0.0001,
    defaultPrice: 0.59200,
    category: 'forex',
    tradingViewSymbol: 'FX:NZDUSD',
    twelveDataSymbol: 'NZD/USD',
    isDecentralizedOrQuoteOnly: true,
  },
  {
    id: 'EURGBP',
    displaySymbol: 'EUR/GBP',
    name: 'Euro / British Pound',
    baseAsset: 'EUR',
    quoteAsset: 'GBP',
    priceDecimals: 5,
    tickSize: 0.0001,
    defaultPrice: 0.83850,
    category: 'forex',
    tradingViewSymbol: 'FX:EURGBP',
    twelveDataSymbol: 'EUR/GBP',
    isDecentralizedOrQuoteOnly: true,
  },
  {
    id: 'EURJPY',
    displaySymbol: 'EUR/JPY',
    name: 'Euro / Japanese Yen',
    baseAsset: 'EUR',
    quoteAsset: 'JPY',
    priceDecimals: 3,
    tickSize: 0.01,
    defaultPrice: 165.620,
    category: 'forex',
    tradingViewSymbol: 'FX:EURJPY',
    twelveDataSymbol: 'EUR/JPY',
    isDecentralizedOrQuoteOnly: true,
  },
  {
    id: 'GBPJPY',
    displaySymbol: 'GBP/JPY',
    name: 'British Pound / Japanese Yen',
    baseAsset: 'GBP',
    quoteAsset: 'JPY',
    priceDecimals: 3,
    tickSize: 0.01,
    defaultPrice: 197.550,
    category: 'forex',
    tradingViewSymbol: 'FX:GBPJPY',
    twelveDataSymbol: 'GBP/JPY',
    isDecentralizedOrQuoteOnly: true,
  },

  // ----------------------------------------------------
  // METALS
  // ----------------------------------------------------
  {
    id: 'XAUUSD',
    displaySymbol: 'XAU/USD',
    name: 'Gold Spot / US Dollar',
    baseAsset: 'XAU',
    quoteAsset: 'USD',
    priceDecimals: 2,
    tickSize: 0.10,
    defaultPrice: 2658.50,
    category: 'metals',
    tradingViewSymbol: 'TVC:GOLD',
    twelveDataSymbol: 'XAU/USD',
    isDecentralizedOrQuoteOnly: true,
  },
  {
    id: 'XAGUSD',
    displaySymbol: 'XAG/USD',
    name: 'Silver Spot / US Dollar',
    baseAsset: 'XAG',
    quoteAsset: 'USD',
    priceDecimals: 3,
    tickSize: 0.01,
    defaultPrice: 31.450,
    category: 'metals',
    tradingViewSymbol: 'TVC:SILVER',
    twelveDataSymbol: 'XAG/USD',
    isDecentralizedOrQuoteOnly: true,
  },

  // ----------------------------------------------------
  // INDICES
  // ----------------------------------------------------
  {
    id: 'US30',
    displaySymbol: 'US30',
    name: 'Wall Street 30 / Dow Jones CFD',
    baseAsset: 'US30',
    quoteAsset: 'USD',
    priceDecimals: 2,
    tickSize: 1.0,
    defaultPrice: 43620.00,
    category: 'indices',
    tradingViewSymbol: 'CURRENCYCOM:US30',
    twelveDataSymbol: 'DJI',
    isDecentralizedOrQuoteOnly: true,
  },
  {
    id: 'NAS100',
    displaySymbol: 'NAS100',
    name: 'US Tech 100 / Nasdaq CFD',
    baseAsset: 'NAS100',
    quoteAsset: 'USD',
    priceDecimals: 2,
    tickSize: 0.50,
    defaultPrice: 20880.00,
    category: 'indices',
    tradingViewSymbol: 'CURRENCYCOM:NAS100',
    twelveDataSymbol: 'IXIC',
    isDecentralizedOrQuoteOnly: true,
  },
  {
    id: 'SPX500',
    displaySymbol: 'SPX500',
    name: 'US 500 / S&P 500 CFD',
    baseAsset: 'SPX500',
    quoteAsset: 'USD',
    priceDecimals: 2,
    tickSize: 0.25,
    defaultPrice: 5885.00,
    category: 'indices',
    tradingViewSymbol: 'CURRENCYCOM:US500',
    twelveDataSymbol: 'SPX',
    isDecentralizedOrQuoteOnly: true,
  },
  {
    id: 'GER40',
    displaySymbol: 'GER40',
    name: 'Germany 40 / DAX CFD',
    baseAsset: 'GER40',
    quoteAsset: 'EUR',
    priceDecimals: 2,
    tickSize: 1.0,
    defaultPrice: 19420.00,
    category: 'indices',
    tradingViewSymbol: 'CURRENCYCOM:GER40',
    twelveDataSymbol: 'GDAXI',
    isDecentralizedOrQuoteOnly: true,
  },
  {
    id: 'UK100',
    displaySymbol: 'UK100',
    name: 'FTSE 100 CFD',
    baseAsset: 'UK100',
    quoteAsset: 'GBP',
    priceDecimals: 2,
    tickSize: 0.50,
    defaultPrice: 8275.00,
    category: 'indices',
    tradingViewSymbol: 'CURRENCYCOM:UK100',
    twelveDataSymbol: 'FTSE',
    isDecentralizedOrQuoteOnly: true,
  },

  // ----------------------------------------------------
  // CRYPTO (Centralized Order Flow with Direct Aggressors)
  // ----------------------------------------------------
  {
    id: 'BTCUSD',
    displaySymbol: 'BTC/USD',
    name: 'Bitcoin / US Dollar',
    baseAsset: 'BTC',
    quoteAsset: 'USDT',
    priceDecimals: 2,
    tickSize: 1.0,
    defaultPrice: 104250.00,
    category: 'crypto',
    tradingViewSymbol: 'BINANCE:BTCUSDT',
    twelveDataSymbol: 'BTC/USD',
    binanceSymbol: 'btcusdt',
    isDecentralizedOrQuoteOnly: false,
  },
  {
    id: 'ETHUSD',
    displaySymbol: 'ETH/USD',
    name: 'Ethereum / US Dollar',
    baseAsset: 'ETH',
    quoteAsset: 'USDT',
    priceDecimals: 2,
    tickSize: 0.25,
    defaultPrice: 3860.00,
    category: 'crypto',
    tradingViewSymbol: 'BINANCE:ETHUSDT',
    twelveDataSymbol: 'ETH/USD',
    binanceSymbol: 'ethusdt',
    isDecentralizedOrQuoteOnly: false,
  },
  {
    id: 'SOLUSD',
    displaySymbol: 'SOL/USD',
    name: 'Solana / US Dollar',
    baseAsset: 'SOL',
    quoteAsset: 'USDT',
    priceDecimals: 2,
    tickSize: 0.05,
    defaultPrice: 248.50,
    category: 'crypto',
    tradingViewSymbol: 'BINANCE:SOLUSDT',
    twelveDataSymbol: 'SOL/USD',
    binanceSymbol: 'solusdt',
    isDecentralizedOrQuoteOnly: false,
  },
  {
    id: 'BNBUSD',
    displaySymbol: 'BNB/USD',
    name: 'BNB / US Dollar',
    baseAsset: 'BNB',
    quoteAsset: 'USDT',
    priceDecimals: 2,
    tickSize: 0.10,
    defaultPrice: 685.00,
    category: 'crypto',
    tradingViewSymbol: 'BINANCE:BNBUSDT',
    twelveDataSymbol: 'BNB/USD',
    binanceSymbol: 'bnbusdt',
    isDecentralizedOrQuoteOnly: false,
  },
  {
    id: 'XRPUSD',
    displaySymbol: 'XRP/USD',
    name: 'XRP / US Dollar',
    baseAsset: 'XRP',
    quoteAsset: 'USDT',
    priceDecimals: 4,
    tickSize: 0.001,
    defaultPrice: 2.3500,
    category: 'crypto',
    tradingViewSymbol: 'BINANCE:XRPUSDT',
    twelveDataSymbol: 'XRP/USD',
    binanceSymbol: 'xrpusdt',
    isDecentralizedOrQuoteOnly: false,
  },
  {
    id: 'ADAUSD',
    displaySymbol: 'ADA/USD',
    name: 'Cardano / US Dollar',
    baseAsset: 'ADA',
    quoteAsset: 'USDT',
    priceDecimals: 4,
    tickSize: 0.001,
    defaultPrice: 0.9850,
    category: 'crypto',
    tradingViewSymbol: 'BINANCE:ADAUSDT',
    twelveDataSymbol: 'ADA/USD',
    binanceSymbol: 'adausdt',
    isDecentralizedOrQuoteOnly: false,
  },

  // ----------------------------------------------------
  // STOCKS
  // ----------------------------------------------------
  {
    id: 'AAPL',
    displaySymbol: 'AAPL',
    name: 'Apple Inc.',
    baseAsset: 'AAPL',
    quoteAsset: 'USD',
    priceDecimals: 2,
    tickSize: 0.01,
    defaultPrice: 232.80,
    category: 'stocks',
    tradingViewSymbol: 'NASDAQ:AAPL',
    twelveDataSymbol: 'AAPL',
    isDecentralizedOrQuoteOnly: true,
  },
  {
    id: 'MSFT',
    displaySymbol: 'MSFT',
    name: 'Microsoft Corporation',
    baseAsset: 'MSFT',
    quoteAsset: 'USD',
    priceDecimals: 2,
    tickSize: 0.01,
    defaultPrice: 428.50,
    category: 'stocks',
    tradingViewSymbol: 'NASDAQ:MSFT',
    twelveDataSymbol: 'MSFT',
    isDecentralizedOrQuoteOnly: true,
  },
  {
    id: 'NVDA',
    displaySymbol: 'NVDA',
    name: 'NVIDIA Corporation',
    baseAsset: 'NVDA',
    quoteAsset: 'USD',
    priceDecimals: 2,
    tickSize: 0.01,
    defaultPrice: 139.60,
    category: 'stocks',
    tradingViewSymbol: 'NASDAQ:NVDA',
    twelveDataSymbol: 'NVDA',
    isDecentralizedOrQuoteOnly: true,
  },
  {
    id: 'TSLA',
    displaySymbol: 'TSLA',
    name: 'Tesla, Inc.',
    baseAsset: 'TSLA',
    quoteAsset: 'USD',
    priceDecimals: 2,
    tickSize: 0.01,
    defaultPrice: 246.20,
    category: 'stocks',
    tradingViewSymbol: 'NASDAQ:TSLA',
    twelveDataSymbol: 'TSLA',
    isDecentralizedOrQuoteOnly: true,
  },
  {
    id: 'AMZN',
    displaySymbol: 'AMZN',
    name: 'Amazon.com, Inc.',
    baseAsset: 'AMZN',
    quoteAsset: 'USD',
    priceDecimals: 2,
    tickSize: 0.01,
    defaultPrice: 208.40,
    category: 'stocks',
    tradingViewSymbol: 'NASDAQ:AMZN',
    twelveDataSymbol: 'AMZN',
    isDecentralizedOrQuoteOnly: true,
  },
  {
    id: 'META',
    displaySymbol: 'META',
    name: 'Meta Platforms, Inc.',
    baseAsset: 'META',
    quoteAsset: 'USD',
    priceDecimals: 2,
    tickSize: 0.01,
    defaultPrice: 588.30,
    category: 'stocks',
    tradingViewSymbol: 'NASDAQ:META',
    twelveDataSymbol: 'META',
    isDecentralizedOrQuoteOnly: true,
  },
];

/**
 * Normalization helper: resolves any raw string input (e.g. "EUR/USD", "eurusd", "BTC-USD", "XAUUSD")
 * into a canonical SymbolInfo object.
 */
export function normalizeSymbol(rawInput: string): SymbolInfo {
  if (!rawInput) return SUPPORTED_SYMBOLS[0];
  const cleaned = rawInput.toUpperCase().replace(/[\/\-_: ]/g, '');

  // Exact ID match
  const matchId = SUPPORTED_SYMBOLS.find(
    s => s.id.toUpperCase().replace(/[\/\-_: ]/g, '') === cleaned
  );
  if (matchId) return matchId;

  // Display symbol match
  const matchDisplay = SUPPORTED_SYMBOLS.find(
    s => s.displaySymbol.toUpperCase().replace(/[\/\-_: ]/g, '') === cleaned
  );
  if (matchDisplay) return matchDisplay;

  // Base asset match
  const matchBase = SUPPORTED_SYMBOLS.find(
    s => s.baseAsset.toUpperCase() === cleaned
  );
  if (matchBase) return matchBase;

  // TradingView symbol match
  const matchTv = SUPPORTED_SYMBOLS.find(
    s => s.tradingViewSymbol.toUpperCase().replace(/[\/\-_: ]/g, '').includes(cleaned)
  );
  if (matchTv) return matchTv;

  return SUPPORTED_SYMBOLS[0];
}

export function getSymbolInfo(symbolId: string): SymbolInfo {
  return normalizeSymbol(symbolId);
}
